language: generic

os:
  - linux
  - osx

dist: trusty
sudo: required

env:
  global:
    # 3.4_bugfix is not safe-string compatible
    - OCAMLPARAM="safe-string=0,_"

install:
  # Install dependencies
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo add-apt-repository ppa:haxe/ocaml -y;
      sudo apt-get update -qq;
      sudo apt-get install ocaml camlp4 zlib1g-dev -qqy;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      travis_retry brew update;
      travis_retry brew install ocaml camlp4;
    fi

script:
  - make
